name: publish on Github & Modrinth
on: [workflow_dispatch]

env:
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env
      - uses: actions/checkout@v4
      - name: Set up jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew clean build
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3.3
        with:
          modrinth-id: un7urasP
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-token: "${{env.GITHUB_TOKEN}}"

